name: LFT Report

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run FHIR server
        run: docker run -d --network="host" -p 8080:8080 hapiproject/hapi:v6.2.2

      - name: Ping FHIR server
        run: sleep 120; curl http://localhost:8080/fhir/metadata