name: LFT Report

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - run: pip install requests jinja2 pdfkit fhir.resources

      - name: Install wkhtmltopdf
        run: sudo apt install -y wkhtmltopdf

      - name: Copy UKCore package to folder for docker mount
        run: mkdir ~/package; cp packages/0.0.8-pre-release.tgz ~/package/package.tgz

      - name: Run FHIR server (Loading package, but not currently using validate endpoint - TODO)
        run: docker run -d -v ~/package:/package -p 8080:8080 -e hapi.fhir.daoconfig_client_id_strategy=UUID -e hapi.fhir.client_id_strategy=ANY -e hapi.fhir.implementationguides.ukcore.name=fhir.r4.ukcore.stu3.currentbuild -e hapi.fhir.implementationguides.ukcore.version=0.0.8-pre-release -e hapi.fhir.implementationguides.ukcore.url=file:///package/package.tgz hapiproject/hapi:latest

      - name: Sleep to give server time to start
        run: sleep 120

      - name: Create the LFT request
        run: curl -X POST -H "Content-type:application/fhir+json;fhirVersion=4.0" -d @resources/TRANSACTION-path-R4-example-bundle-LFT-UandE-request.json http://localhost:8080/fhir

      - name: Update the LFT request with Observations
        run: curl -X POST -H "Content-type:application/fhir+json;fhirVersion=4.0" -d @resources/TRANSACTION-path-R4-example-bundle-LFT-UandE-report.json http://localhost:8080/fhir

      - name: Create the Laboratory Report using custom Operation (_query not supported on HAPI STARTER yet)
        run: python operations/document/document.py

      - name: Query the Document Bundle
        run: sleep 30; curl http://localhost:8080/fhir/Bundle?identifier=REP-20220308-008902 | jq '.entry[0].resource' > LFT_Laboratory_Report_Custom_Operation.json

      - name: Validate custom Document Bundle with UKCore
        run: java -jar validator_cli.jar LFT_Laboratory_Report_Custom_Operation.json -ig packages/0.0.8-pre-release.tgz -sct uk -html-output LFT_Laboratory_Report_UKCore_Validation.html

      - name: Put corresponding example Composition resource for report
        run: curl -X PUT -H "Content-type:application/fhir+json;fhirVersion=4.0" -d @resources/path-R4-example-composition-LFT-UandE-example.json http://localhost:8080/fhir/Composition/138ffee6-fbc1-49e2-bfbc-e14b777ab62a

      - name: Persist the Document Bundle with GET on $document
        run: curl http://localhost:8080/fhir/Composition/138ffee6-fbc1-49e2-bfbc-e14b777ab62a/\$document?persist=true > LFT_Laboratory_Report_HAPI_document_Operation.json

      - name: Render the report in html and pdf
        run: cd operations/render; python render.py -d ../../LFT_Laboratory_Report_Custom_Operation.json -t report.j2 -o ../../LFT_Laboratory_Report

      - name: Output the Document Bundle generated with the $document operation
        uses: actions/upload-artifact@v3
        with:
          name: LFT_Laboratory_Report_Examples
          path: LFT_Laboratory_Report*