name: LFT Report

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - run: pip install requests

      - name: Run FHIR server
        run: docker run -d --network="host" -v ~/package:/package -p 8080:8080 -e hapi.fhir.implementationguides.ukcore.name=fhir.r4.ukcore.stu3.currentbuild -e hapi.fhir.implementationguides.ukcore.version=0.0.3-pre-release -e hapi.fhir.implementationguides.ukcore.url=file:///package/ukcore-0.0.3-pre-release.tgz hapiproject/hapi:v6.2.2

      - name: Sleep to give server time to start
        run: sleep 120

      - name: Create the LFT request
        run: curl -X POST -H "Content-type:application/fhir+json;fhirVersion=4.0" -d @resources/TRANSACTION-path-R4-example-bundle-LFT-UandE-request.json http://localhost:8080/fhir

      - name: Update the LFT request with Observations
        run: curl -X POST -H "Content-type:application/fhir+json;fhirVersion=4.0" -d @resources/TRANSACTION-path-R4-example-bundle-LFT-UandE-report.json http://localhost:8080/fhir

      - name: Create the Laboratory Report
        run: python operations/report.py

      - name: Query the Document Bundle
        run: sleep 30; curl http://localhost:8080/fhir/Bundle?identifier=REP-20220308-008902 | jq '.entry[0].resource' > LFT_Laboratory_Report.json

      - name: Output the Document Bundle
        uses: actions/upload-artifact@v3
        with:
          name: LFT_Laboratory_Report
          path: LFT_Laboratory_Report.json