name: LFT Report

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - run: pip install requests

      - name: Copy UKCore package to folder for docker mount
        run: mkdir ~/package; cp packages/ukcore-0.0.3-pre-release_with-precalculated-snapshots.tgz ~/package 

      - name: Run FHIR server
        run: docker run -d -v ~/package:/package -p 8080:8080 -e hapi.fhir.daoconfig_client_id_strategy=UUID -e hapi.fhir.client_id_strategy=ANY -e hapi.fhir.implementationguides.ukcore.name=fhir.r4.ukcore.stu3.currentbuild -e hapi.fhir.implementationguides.ukcore.version=0.0.3-pre-release -e hapi.fhir.implementationguides.ukcore.url=file:///package/ukcore-0.0.3-pre-release_with-precalculated-snapshots.tgz hapiproject/hapi:v6.2.2

      - name: Sleep to give server time to start
        run: sleep 120

      - name: Create the LFT request
        run: curl -X POST -H "Content-type:application/fhir+json;fhirVersion=4.0" -d @resources/TRANSACTION-path-R4-example-bundle-LFT-UandE-request.json http://localhost:8080/fhir

      - name: Update the LFT request with Observations
        run: curl -X POST -H "Content-type:application/fhir+json;fhirVersion=4.0" -d @resources/TRANSACTION-path-R4-example-bundle-LFT-UandE-report.json http://localhost:8080/fhir

      - name: Create the Laboratory Report using custom Operation (_query not supported on HAPI STARTER yet)
        run: python operations/document.py

      - name: Query the Document Bundle
        run: sleep 30; curl http://localhost:8080/fhir/Bundle?identifier=REP-20220308-008902 | jq '.entry[0].resource' > LFT_Laboratory_Report_Custom_Operation.json

      - name: Put corresponding example Composition resource for report
        run: curl -X PUT -H "Content-type:application/fhir+json;fhirVersion=4.0" -d @resources/path-R4-example-composition-LFT-UandE-report.json http://localhost:8080/fhir/Composition/138ffee6-fbc1-49e2-bfbc-e14b777ab62a

      - name: Persist the Document Bundle with GET on $document
        run: curl http://localhost:8080/fhir/Composition/138ffee6-fbc1-49e2-bfbc-e14b777ab62a/\$document?persist=true > LFT_Laboratory_Report_HAPI_document_Operation.json

      - name: Output the Document Bundle generated with the $document operation
        uses: actions/upload-artifact@v3
        with:
          name: LFT_Laboratory_Report_Examples
          path: LFT_Laboratory_Report*